server:
  port: 8852
spring:
  datasource:
    url: jdbc:mysql://121.199.44.220:3306/nunumao?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    username: root
    password: 9fsgobvcHzQrTi6U
# swagger 接口文档
swagger:
  # 开启访问
  enable: false